name: Daily Feed Refresh

on:
  workflow_dispatch:
  schedule:
    # run every day at 23:18 UTC
    # random time when runners should be available
    - cron: '18 23 * * *'

permissions:
  contents: write

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Sparse Checkout Repository
        uses: actions/checkout@v5
        with:
          sparse-checkout: '.'

      - name: Install Nushell
        uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: nushell/nushell
          tag: 0.109.1

      - id: date
        name: Format Date For Commit Message
        env:
          TZ: 'America/New_York'
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
          echo "datetime=$(date +'%Y-%m-%d %H:%M %Z')" >> "$GITHUB_OUTPUT"

      - name: Run Update Feeds Script
        run: nu gha_update_feeds.nu

      - name: Commit & Push Changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          add_options: --sparse
          commit_message: ${{ github.event_name == 'workflow_dispatch'
            && format('Manual Feed Refresh - {0}', steps.date.outputs.datetime)
            || format('Automated Feed Refresh - {0}', steps.date.outputs.date) }}
          commit_author: ${{ github.event_name == 'workflow_dispatch'
            && format('{0} <{1}+{0}@users.noreply.github.com>', github.actor, github.actor_id)
            || 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
            }}
